os: linux
dist: trusty
sudo: required
language: node_js
node_js: stable
before_script:
  - sudo apt-get install wine -qq
script:
  - yarn --link-duplicates
  - node ./build
  - yarn build -w nsis --pd \"./knitting/MUSICOINApp-win32-x64/\""
deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  file_glob: true
  file: './dist/*'
  on:
    repo: etaletai13/MUSICOINApp
    branch: windows
