os: linux
language: node_js
node_js: stable
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
script:
    - yarn --link-duplicates
    - node ./knit
    - yarn build -l deb --pd './knitting/musicoin-app-linux-x64'
deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  file: './dist/MUSICOINApp_1.0.0_amd64.deb'
  on:
    repo: etaletai13/MUSICOINApp
    branch: linux
